# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unit_demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 831)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 30, 1091, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.bt_sign_in = QtWidgets.QPushButton(self.page_5)
        self.bt_sign_in.setGeometry(QtCore.QRect(560, 190, 211, 201))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.bt_sign_in.setFont(font)
        self.bt_sign_in.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 217, 180);\n"
"    \n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 180, 154);\n"
"}")
        self.bt_sign_in.setText("")
        self.bt_sign_in.setObjectName("bt_sign_in")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 530, 311, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(320, 530, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 205, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        self.label_2.setGeometry(QtCore.QRect(770, -530, 501, 621))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.page_5)
        self.frame_2.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Bt_wrong = QtWidgets.QPushButton(self.frame_2)
        self.Bt_wrong.setGeometry(QtCore.QRect(50, 360, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_wrong.setFont(font)
        self.Bt_wrong.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong.setObjectName("Bt_wrong")
        self.Bt_exercise = QtWidgets.QPushButton(self.frame_2)
        self.Bt_exercise.setGeometry(QtCore.QRect(50, 220, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise.setFont(font)
        self.Bt_exercise.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise.setObjectName("Bt_exercise")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 70, 221, 80))
        self.frame_5.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.Bt_main = QtWidgets.QPushButton(self.frame_5)
        self.Bt_main.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_main.setFont(font)
        self.Bt_main.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_main.setObjectName("Bt_main")
        self.Bt_setting = QtWidgets.QPushButton(self.frame_2)
        self.Bt_setting.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting.setFont(font)
        self.Bt_setting.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting.setObjectName("Bt_setting")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(630, 260, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.page_5)
        self.frame_3.setGeometry(QtCore.QRect(960, 20, 101, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_sign_in = QtWidgets.QLabel(self.page_5)
        self.label_sign_in.setEnabled(True)
        self.label_sign_in.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_sign_in.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_sign_in.setText("")
        self.label_sign_in.setObjectName("label_sign_in")
        self.label_sign_in.raise_()
        self.bt_sign_in.raise_()
        self.pushButton_3.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_9 = QtWidgets.QFrame(self.page_2)
        self.frame_9.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_9.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.Bt_wrong_1 = QtWidgets.QPushButton(self.frame_9)
        self.Bt_wrong_1.setGeometry(QtCore.QRect(50, 360, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_wrong_1.setFont(font)
        self.Bt_wrong_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong_1.setObjectName("Bt_wrong_1")
        self.Bt_setting_1 = QtWidgets.QPushButton(self.frame_9)
        self.Bt_setting_1.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting_1.setFont(font)
        self.Bt_setting_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting_1.setObjectName("Bt_setting_1")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(0, 220, 221, 80))
        self.frame_10.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.Bt_exercise_1 = QtWidgets.QPushButton(self.frame_10)
        self.Bt_exercise_1.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_exercise_1.setFont(font)
        self.Bt_exercise_1.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_exercise_1.setObjectName("Bt_exercise_1")
        self.Bt_main_1 = QtWidgets.QPushButton(self.frame_9)
        self.Bt_main_1.setGeometry(QtCore.QRect(50, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_main_1.setFont(font)
        self.Bt_main_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_main_1.setObjectName("Bt_main_1")
        self.frame_10.raise_()
        self.Bt_wrong_1.raise_()
        self.Bt_setting_1.raise_()
        self.Bt_main_1.raise_()
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(960, 20, 101, 111))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_7.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_3.setGeometry(QtCore.QRect(280, 90, 741, 611))
        self.stackedWidget_3.setStyleSheet("background-color: rgb(94,159,150);")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.ex_class5_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class5_2.setGeometry(QtCore.QRect(470, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class5_2.setFont(font)
        self.ex_class5_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(170, 85, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class5_2.setObjectName("ex_class5_2")
        self.ex_class3_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class3_2.setGeometry(QtCore.QRect(120, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class3_2.setFont(font)
        self.ex_class3_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(170, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class3_2.setObjectName("ex_class3_2")
        self.ex_class2_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class2_2.setGeometry(QtCore.QRect(120, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class2_2.setFont(font)
        self.ex_class2_2.setAutoFillBackground(False)
        self.ex_class2_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class2_2.setObjectName("ex_class2_2")
        self.ex_class6_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class6_2.setGeometry(QtCore.QRect(470, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class6_2.setFont(font)
        self.ex_class6_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class6_2.setObjectName("ex_class6_2")
        self.exercise_class_2 = QtWidgets.QLabel(self.page_6)
        self.exercise_class_2.setGeometry(QtCore.QRect(300, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exercise_class_2.setFont(font)
        self.exercise_class_2.setStyleSheet("")
        self.exercise_class_2.setObjectName("exercise_class_2")
        self.ex_class4_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class4_2.setGeometry(QtCore.QRect(470, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class4_2.setFont(font)
        self.ex_class4_2.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(0, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class4_2.setObjectName("ex_class4_2")
        self.ex_class1_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class1_2.setGeometry(QtCore.QRect(120, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class1_2.setFont(font)
        self.ex_class1_2.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class1_2.setObjectName("ex_class1_2")
        self.stackedWidget_3.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_3.addWidget(self.page_7)
        self.label_drag_2 = QtWidgets.QLabel(self.page_2)
        self.label_drag_2.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_drag_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag_2.setText("")
        self.label_drag_2.setObjectName("label_drag_2")
        self.label_drag_2.raise_()
        self.stackedWidget_3.raise_()
        self.frame_7.raise_()
        self.frame_9.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_drag = QtWidgets.QLabel(self.page)
        self.label_drag.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_drag.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag.setText("")
        self.label_drag.setObjectName("label_drag")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page)
        self.stackedWidget_2.setGeometry(QtCore.QRect(280, 90, 741, 611))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(94,159,150);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.ex_class5 = QtWidgets.QPushButton(self.page_3)
        self.ex_class5.setGeometry(QtCore.QRect(470, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class5.setFont(font)
        self.ex_class5.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(170, 85, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class5.setObjectName("ex_class5")
        self.ex_class3 = QtWidgets.QPushButton(self.page_3)
        self.ex_class3.setGeometry(QtCore.QRect(120, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class3.setFont(font)
        self.ex_class3.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(170, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class3.setObjectName("ex_class3")
        self.ex_class2 = QtWidgets.QPushButton(self.page_3)
        self.ex_class2.setGeometry(QtCore.QRect(120, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class2.setFont(font)
        self.ex_class2.setAutoFillBackground(False)
        self.ex_class2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class2.setObjectName("ex_class2")
        self.ex_class6 = QtWidgets.QPushButton(self.page_3)
        self.ex_class6.setGeometry(QtCore.QRect(470, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class6.setFont(font)
        self.ex_class6.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class6.setObjectName("ex_class6")
        self.exercise_class = QtWidgets.QLabel(self.page_3)
        self.exercise_class.setGeometry(QtCore.QRect(300, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exercise_class.setFont(font)
        self.exercise_class.setStyleSheet("")
        self.exercise_class.setObjectName("exercise_class")
        self.ex_class4 = QtWidgets.QPushButton(self.page_3)
        self.ex_class4.setGeometry(QtCore.QRect(470, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class4.setFont(font)
        self.ex_class4.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(0, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class4.setObjectName("ex_class4")
        self.ex_class1 = QtWidgets.QPushButton(self.page_3)
        self.ex_class1.setGeometry(QtCore.QRect(120, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class1.setFont(font)
        self.ex_class1.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class1.setObjectName("ex_class1")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_6.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.Bt_exercise_2 = QtWidgets.QPushButton(self.frame_6)
        self.Bt_exercise_2.setGeometry(QtCore.QRect(50, 220, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise_2.setFont(font)
        self.Bt_exercise_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise_2.setObjectName("Bt_exercise_2")
        self.Bt_setting_2 = QtWidgets.QPushButton(self.frame_6)
        self.Bt_setting_2.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting_2.setFont(font)
        self.Bt_setting_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting_2.setObjectName("Bt_setting_2")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(0, 360, 221, 80))
        self.frame_8.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Bt_wrong_2 = QtWidgets.QPushButton(self.frame_8)
        self.Bt_wrong_2.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_wrong_2.setFont(font)
        self.Bt_wrong_2.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_wrong_2.setObjectName("Bt_wrong_2")
        self.Bt_main_2 = QtWidgets.QPushButton(self.frame_6)
        self.Bt_main_2.setGeometry(QtCore.QRect(50, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_main_2.setFont(font)
        self.Bt_main_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_main_2.setObjectName("Bt_main_2")
        self.frame_8.raise_()
        self.Bt_exercise_2.raise_()
        self.Bt_setting_2.raise_()
        self.Bt_main_2.raise_()
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(960, 20, 101, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.stackedWidget.addWidget(self.page)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.frame_12 = QtWidgets.QFrame(self.page_8)
        self.frame_12.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_12.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.Bt_wrong_3 = QtWidgets.QPushButton(self.frame_12)
        self.Bt_wrong_3.setGeometry(QtCore.QRect(50, 360, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_wrong_3.setFont(font)
        self.Bt_wrong_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong_3.setObjectName("Bt_wrong_3")
        self.Bt_exercise_3 = QtWidgets.QPushButton(self.frame_12)
        self.Bt_exercise_3.setGeometry(QtCore.QRect(50, 220, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise_3.setFont(font)
        self.Bt_exercise_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise_3.setObjectName("Bt_exercise_3")
        self.Bt_main_3 = QtWidgets.QPushButton(self.frame_12)
        self.Bt_main_3.setGeometry(QtCore.QRect(50, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_main_3.setFont(font)
        self.Bt_main_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_main_3.setObjectName("Bt_main_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(0, 500, 221, 80))
        self.frame_14.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.Bt_setting_3 = QtWidgets.QPushButton(self.frame_14)
        self.Bt_setting_3.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_setting_3.setFont(font)
        self.Bt_setting_3.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_setting_3.setObjectName("Bt_setting_3")
        self.frame_14.raise_()
        self.Bt_wrong_3.raise_()
        self.Bt_exercise_3.raise_()
        self.Bt_main_3.raise_()
        self.Bt_newacount = QtWidgets.QPushButton(self.page_8)
        self.Bt_newacount.setGeometry(QtCore.QRect(320, 530, 701, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_newacount.setFont(font)
        self.Bt_newacount.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_newacount.setObjectName("Bt_newacount")
        self.Bt_email = QtWidgets.QPushButton(self.page_8)
        self.Bt_email.setGeometry(QtCore.QRect(320, 370, 701, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_email.setFont(font)
        self.Bt_email.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_email.setObjectName("Bt_email")
        self.frame_11 = QtWidgets.QFrame(self.page_8)
        self.frame_11.setGeometry(QtCore.QRect(960, 30, 91, 121))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_8.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_9.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.Bt_setting_5 = QtWidgets.QPushButton(self.page_8)
        self.Bt_setting_5.setGeometry(QtCore.QRect(320, 450, 701, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting_5.setFont(font)
        self.Bt_setting_5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting_5.setObjectName("Bt_setting_5")
        self.label_4 = QtWidgets.QLabel(self.page_8)
        self.label_4.setGeometry(QtCore.QRect(600, 130, 141, 141))
        self.label_4.setStyleSheet("border-radius:60px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_drag_3 = QtWidgets.QLabel(self.page_8)
        self.label_drag_3.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_drag_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag_3.setText("")
        self.label_drag_3.setObjectName("label_drag_3")
        self.label_drag_3.raise_()
        self.Bt_setting_5.raise_()
        self.Bt_newacount.raise_()
        self.frame_11.raise_()
        self.Bt_email.raise_()
        self.label_4.raise_()
        self.frame_12.raise_()
        self.stackedWidget.addWidget(self.page_8)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.pushButton.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_2.clicked.connect(Form.close) # type: ignore
        self.pushButton_6.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_7.clicked.connect(Form.close) # type: ignore
        self.pushButton_4.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_5.clicked.connect(Form.close) # type: ignore
        self.pushButton_8.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_9.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_3.setText(_translate("Form", "日历"))
        self.label.setText(_translate("Form", "刷题进度："))
        self.Bt_wrong.setText(_translate("Form", "错题"))
        self.Bt_exercise.setText(_translate("Form", "练习"))
        self.Bt_main.setText(_translate("Form", "首页"))
        self.Bt_setting.setText(_translate("Form", "我的"))
        self.label_3.setText(_translate("Form", "签到"))
        self.Bt_wrong_1.setText(_translate("Form", "错题"))
        self.Bt_setting_1.setText(_translate("Form", "我的"))
        self.Bt_exercise_1.setText(_translate("Form", "练习"))
        self.Bt_main_1.setText(_translate("Form", "首页"))
        self.ex_class5_2.setText(_translate("Form", "分类5"))
        self.ex_class3_2.setText(_translate("Form", "分类3"))
        self.ex_class2_2.setText(_translate("Form", "分类2"))
        self.ex_class6_2.setText(_translate("Form", "分类6"))
        self.exercise_class_2.setText(_translate("Form", "练习类别"))
        self.ex_class4_2.setText(_translate("Form", "分类4"))
        self.ex_class1_2.setText(_translate("Form", "分类1"))
        self.ex_class5.setText(_translate("Form", "分类5"))
        self.ex_class3.setText(_translate("Form", "分类3"))
        self.ex_class2.setText(_translate("Form", "分类2"))
        self.ex_class6.setText(_translate("Form", "分类6"))
        self.exercise_class.setText(_translate("Form", "错题类别"))
        self.ex_class4.setText(_translate("Form", "分类4"))
        self.ex_class1.setText(_translate("Form", "分类1"))
        self.Bt_exercise_2.setText(_translate("Form", "练习"))
        self.Bt_setting_2.setText(_translate("Form", "我的"))
        self.Bt_wrong_2.setText(_translate("Form", "错题"))
        self.Bt_main_2.setText(_translate("Form", "首页"))
        self.Bt_wrong_3.setText(_translate("Form", "错题"))
        self.Bt_exercise_3.setText(_translate("Form", "练习"))
        self.Bt_main_3.setText(_translate("Form", "首页"))
        self.Bt_setting_3.setText(_translate("Form", "我的"))
        self.Bt_newacount.setText(_translate("Form", "切换账号"))
        self.Bt_email.setText(_translate("Form", "个人邮箱"))
        self.Bt_setting_5.setText(_translate("Form", "设置"))
        self.label_4.setText(_translate("Form", "     picture"))
import resource_rc
