# Generated by Django 4.2.6 on 2023-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
