# Generated by Django 4.2.6 on 2023-11-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_computernetworksquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=32, null=True, verbose_name='密码'),
        ),
    ]
