# Generated by Django 4.2.6 on 2023-12-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerNetworksQuestion',
        ),
        migrations.DeleteModel(
            name='ComputerOrganizationAndArchitectureQuestion',
        ),
        migrations.DeleteModel(
            name='DataStructQuestion',
        ),
        migrations.DeleteModel(
            name='EnglishQuestion',
        ),
        migrations.DeleteModel(
            name='MathQuestion',
        ),
        migrations.DeleteModel(
            name='OperatingSystemQuestion',
        ),
        migrations.DeleteModel(
            name='PoliticsQuestion',
        ),
    ]
