# Generated by Django 4.2.6 on 2023-12-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_question_question_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
