# Generated by Django 4.2.6 on 2023-11-22 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='手机号格式不正确', regex='/^1(3[0-9]|4[01456879]|5[0-35-9]|6[2567]|7[0-8]|8[0-9]|9[0-35-9])\\d{8}$/')], verbose_name='手机号')),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='密码长度不能少于10个字符')], verbose_name='密码')),
                ('user_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='头像')),
            ],
        ),
    ]
