# Generated by Django 4.2.6 on 2023-12-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_picture',
            field=models.BinaryField(blank=True, null=True, verbose_name='题目图片'),
        ),
    ]
