# Generated by Django 4.2.6 on 2023-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='选项1'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='选项2'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='选项3'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='选项4'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_5',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='选项5'),
        ),
    ]
