# Generated by Django 4.2.6 on 2023-12-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mistakes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mistakes',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
