# Generated by Django 4.2.6 on 2023-12-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_question_mistakes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mistakes',
            unique_together={('user_id', 'question_id')},
        ),
    ]
