# Generated by Django 4.2.6 on 2023-12-28 13:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_profile_picture_userprofile_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to="upload/", verbose_name='头像'),
        ),
    ]
