# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unit_demo2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 831)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 30, 1091, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.bt_sign_in = QtWidgets.QPushButton(self.page_5)
        self.bt_sign_in.setGeometry(QtCore.QRect(560, 190, 211, 201))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.bt_sign_in.setFont(font)
        self.bt_sign_in.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 217, 180);\n"
"    \n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 180, 154);\n"
"}")
        self.bt_sign_in.setText("")
        self.bt_sign_in.setObjectName("bt_sign_in")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 530, 311, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(320, 530, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 205, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        self.label_2.setGeometry(QtCore.QRect(770, -530, 501, 621))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.page_5)
        self.frame_2.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Bt_wrong = QtWidgets.QPushButton(self.frame_2)
        self.Bt_wrong.setGeometry(QtCore.QRect(50, 360, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_wrong.setFont(font)
        self.Bt_wrong.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong.setObjectName("Bt_wrong")
        self.Bt_exercise = QtWidgets.QPushButton(self.frame_2)
        self.Bt_exercise.setGeometry(QtCore.QRect(50, 220, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise.setFont(font)
        self.Bt_exercise.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise.setObjectName("Bt_exercise")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 70, 221, 80))
        self.frame_5.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.Bt_main = QtWidgets.QPushButton(self.frame_5)
        self.Bt_main.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_main.setFont(font)
        self.Bt_main.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_main.setObjectName("Bt_main")
        self.Bt_setting = QtWidgets.QPushButton(self.frame_2)
        self.Bt_setting.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting.setFont(font)
        self.Bt_setting.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting.setObjectName("Bt_setting")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(630, 260, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.page_5)
        self.frame_3.setGeometry(QtCore.QRect(960, 20, 101, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_sign_in = QtWidgets.QLabel(self.page_5)
        self.label_sign_in.setEnabled(True)
        self.label_sign_in.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_sign_in.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_sign_in.setText("")
        self.label_sign_in.setObjectName("label_sign_in")
        self.label_sign_in.raise_()
        self.bt_sign_in.raise_()
        self.pushButton_3.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_9 = QtWidgets.QFrame(self.page_2)
        self.frame_9.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_9.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.Bt_wrong_1 = QtWidgets.QPushButton(self.frame_9)
        self.Bt_wrong_1.setGeometry(QtCore.QRect(50, 360, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_wrong_1.setFont(font)
        self.Bt_wrong_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong_1.setObjectName("Bt_wrong_1")
        self.Bt_setting_1 = QtWidgets.QPushButton(self.frame_9)
        self.Bt_setting_1.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting_1.setFont(font)
        self.Bt_setting_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting_1.setObjectName("Bt_setting_1")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(0, 220, 221, 80))
        self.frame_10.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.Bt_exercise_1 = QtWidgets.QPushButton(self.frame_10)
        self.Bt_exercise_1.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_exercise_1.setFont(font)
        self.Bt_exercise_1.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_exercise_1.setObjectName("Bt_exercise_1")
        self.Bt_main_1 = QtWidgets.QPushButton(self.frame_9)
        self.Bt_main_1.setGeometry(QtCore.QRect(50, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_main_1.setFont(font)
        self.Bt_main_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_main_1.setObjectName("Bt_main_1")
        self.frame_10.raise_()
        self.Bt_wrong_1.raise_()
        self.Bt_setting_1.raise_()
        self.Bt_main_1.raise_()
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(960, 20, 101, 111))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_7.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(280, 60, 781, 631))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(94,159,150);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.ex_class5_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class5_2.setGeometry(QtCore.QRect(470, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class5_2.setFont(font)
        self.ex_class5_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(170, 85, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class5_2.setObjectName("ex_class5_2")
        self.ex_class3_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class3_2.setGeometry(QtCore.QRect(120, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class3_2.setFont(font)
        self.ex_class3_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(170, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class3_2.setObjectName("ex_class3_2")
        self.ex_class2_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class2_2.setGeometry(QtCore.QRect(120, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class2_2.setFont(font)
        self.ex_class2_2.setAutoFillBackground(False)
        self.ex_class2_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class2_2.setObjectName("ex_class2_2")
        self.ex_class6_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class6_2.setGeometry(QtCore.QRect(470, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class6_2.setFont(font)
        self.ex_class6_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class6_2.setObjectName("ex_class6_2")
        self.exercise_class_2 = QtWidgets.QLabel(self.page_6)
        self.exercise_class_2.setGeometry(QtCore.QRect(300, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exercise_class_2.setFont(font)
        self.exercise_class_2.setStyleSheet("")
        self.exercise_class_2.setObjectName("exercise_class_2")
        self.ex_class4_2 = QtWidgets.QPushButton(self.page_6)
        self.ex_class4_2.setGeometry(QtCore.QRect(470, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class4_2.setFont(font)
        self.ex_class4_2.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(0, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class4_2.setObjectName("ex_class4_2")
        self.ex_class2_1 = QtWidgets.QPushButton(self.page_6)
        self.ex_class2_1.setGeometry(QtCore.QRect(120, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class2_1.setFont(font)
        self.ex_class2_1.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class2_1.setObjectName("ex_class2_1")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.exercise_analyse = QtWidgets.QTextBrowser(self.page_7)
        self.exercise_analyse.setGeometry(QtCore.QRect(10, 490, 531, 151))
        self.exercise_analyse.setStyleSheet("background-color: rgb(94,159,150);")
        self.exercise_analyse.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.exercise_analyse.setObjectName("exercise_analyse")
        self.Bt_A_ex = QtWidgets.QPushButton(self.page_7)
        self.Bt_A_ex.setGeometry(QtCore.QRect(50, 220, 651, 31))
        self.Bt_A_ex.setStyleSheet("QPushButton{\n"
"background-color: rgb(208, 206, 199);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"")
        self.Bt_A_ex.setObjectName("Bt_A_ex")
        self.Bt_D_ex = QtWidgets.QPushButton(self.page_7)
        self.Bt_D_ex.setGeometry(QtCore.QRect(50, 400, 651, 31))
        self.Bt_D_ex.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(208, 206, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_D_ex.setObjectName("Bt_D_ex")
        self.exercise_view = QtWidgets.QPushButton(self.page_7)
        self.exercise_view.setGeometry(QtCore.QRect(660, 60, 71, 41))
        self.exercise_view.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.exercise_view.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color: rgb(198, 237, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"\n"
"")
        self.exercise_view.setObjectName("exercise_view")
        self.Bt_C_ex = QtWidgets.QPushButton(self.page_7)
        self.Bt_C_ex.setGeometry(QtCore.QRect(50, 340, 651, 31))
        self.Bt_C_ex.setStyleSheet("QPushButton{\n"
"background-color: rgb(208, 206, 199);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_C_ex.setObjectName("Bt_C_ex")
        self.exercise_title = QtWidgets.QTextBrowser(self.page_7)
        self.exercise_title.setGeometry(QtCore.QRect(20, 30, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exercise_title.setFont(font)
        self.exercise_title.setStyleSheet("background-color: rgb(94,159,150);\n"
"")
        self.exercise_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.exercise_title.setObjectName("exercise_title")
        self.exercise_next = QtWidgets.QPushButton(self.page_7)
        self.exercise_next.setGeometry(QtCore.QRect(590, 520, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.exercise_next.setFont(font)
        self.exercise_next.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.exercise_next.setObjectName("exercise_next")
        self.Bt_B_ex = QtWidgets.QPushButton(self.page_7)
        self.Bt_B_ex.setGeometry(QtCore.QRect(50, 280, 651, 31))
        self.Bt_B_ex.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(208, 206, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_B_ex.setObjectName("Bt_B_ex")
        self.exercise_back = QtWidgets.QPushButton(self.page_7)
        self.exercise_back.setGeometry(QtCore.QRect(10, 0, 41, 31))
        self.exercise_back.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    border-image: url(:/icon/res/icon/返回.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.exercise_back.setText("")
        self.exercise_back.setObjectName("exercise_back")
        self.exercise_analyse.raise_()
        self.Bt_A_ex.raise_()
        self.Bt_D_ex.raise_()
        self.Bt_C_ex.raise_()
        self.exercise_title.raise_()
        self.exercise_next.raise_()
        self.Bt_B_ex.raise_()
        self.exercise_back.raise_()
        self.exercise_view.raise_()
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.frame = QtWidgets.QFrame(self.page_9)
        self.frame.setGeometry(QtCore.QRect(0, 30, 771, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.exercise_back2 = QtWidgets.QPushButton(self.frame)
        self.exercise_back2.setGeometry(QtCore.QRect(320, 530, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.exercise_back2.setFont(font)
        self.exercise_back2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.exercise_back2.setObjectName("exercise_back2")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 110, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.text_info = QtWidgets.QTextBrowser(self.frame)
        self.text_info.setGeometry(QtCore.QRect(10, 10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_info.setFont(font)
        self.text_info.setStyleSheet("background-color: rgb(94,159,150);")
        self.text_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_info.setObjectName("text_info")
        self.wrong_current = QtWidgets.QTextBrowser(self.frame)
        self.wrong_current.setGeometry(QtCore.QRect(640, 30, 121, 81))
        self.wrong_current.setStyleSheet("background-color: rgb(94,159,150);")
        self.wrong_current.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wrong_current.setObjectName("wrong_current")
        self.wrong_Q1 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q1.setGeometry(QtCore.QRect(70, 150, 51, 51))
        self.wrong_Q1.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q1.setObjectName("wrong_Q1")
        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setGeometry(QtCore.QRect(10, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("border-bottom-left-radius:15px\n"
"\n"
"")
        self.label_title.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_title.setObjectName("label_title")
        self.wrong_Q2 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q2.setGeometry(QtCore.QRect(160, 150, 51, 51))
        self.wrong_Q2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q2.setObjectName("wrong_Q2")
        self.wrong_Q5 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q5.setGeometry(QtCore.QRect(430, 150, 51, 51))
        self.wrong_Q5.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(244, 157, 170);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q5.setObjectName("wrong_Q5")
        self.wrong_Q4 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q4.setGeometry(QtCore.QRect(340, 150, 51, 51))
        self.wrong_Q4.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q4.setObjectName("wrong_Q4")
        self.wrong_Q3 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q3.setGeometry(QtCore.QRect(250, 150, 51, 51))
        self.wrong_Q3.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q3.setObjectName("wrong_Q3")
        self.wrong_Q7 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q7.setGeometry(QtCore.QRect(610, 150, 51, 51))
        self.wrong_Q7.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q7.setObjectName("wrong_Q7")
        self.wrong_Q10 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q10.setGeometry(QtCore.QRect(160, 250, 51, 51))
        self.wrong_Q10.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-radius:15px}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q10.setObjectName("wrong_Q10")
        self.wrong_Q9 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q9.setGeometry(QtCore.QRect(70, 250, 51, 51))
        self.wrong_Q9.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-radius:15px}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q9.setObjectName("wrong_Q9")
        self.wrong_Q8 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q8.setGeometry(QtCore.QRect(700, 150, 51, 51))
        self.wrong_Q8.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(244, 157, 170);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q8.setObjectName("wrong_Q8")
        self.wrong_Q6 = QtWidgets.QPushButton(self.frame)
        self.wrong_Q6.setGeometry(QtCore.QRect(520, 150, 51, 51))
        self.wrong_Q6.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q6.setObjectName("wrong_Q6")
        self.label_answersheet = QtWidgets.QLabel(self.frame)
        self.label_answersheet.setGeometry(QtCore.QRect(330, 50, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_answersheet.setFont(font)
        self.label_answersheet.setObjectName("label_answersheet")
        self.stackedWidget_2.addWidget(self.page_9)
        self.label_drag_2 = QtWidgets.QLabel(self.page_2)
        self.label_drag_2.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_drag_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag_2.setText("")
        self.label_drag_2.setObjectName("label_drag_2")
        self.label_drag_2.raise_()
        self.stackedWidget_2.raise_()
        self.frame_7.raise_()
        self.frame_9.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_drag = QtWidgets.QLabel(self.page)
        self.label_drag.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_drag.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag.setText("")
        self.label_drag.setObjectName("label_drag")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_6.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.Bt_exercise_2 = QtWidgets.QPushButton(self.frame_6)
        self.Bt_exercise_2.setGeometry(QtCore.QRect(50, 220, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise_2.setFont(font)
        self.Bt_exercise_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise_2.setObjectName("Bt_exercise_2")
        self.Bt_setting_2 = QtWidgets.QPushButton(self.frame_6)
        self.Bt_setting_2.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting_2.setFont(font)
        self.Bt_setting_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting_2.setObjectName("Bt_setting_2")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(0, 360, 221, 80))
        self.frame_8.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Bt_wrong_2 = QtWidgets.QPushButton(self.frame_8)
        self.Bt_wrong_2.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_wrong_2.setFont(font)
        self.Bt_wrong_2.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_wrong_2.setObjectName("Bt_wrong_2")
        self.Bt_main_2 = QtWidgets.QPushButton(self.frame_6)
        self.Bt_main_2.setGeometry(QtCore.QRect(50, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_main_2.setFont(font)
        self.Bt_main_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_main_2.setObjectName("Bt_main_2")
        self.frame_8.raise_()
        self.Bt_exercise_2.raise_()
        self.Bt_setting_2.raise_()
        self.Bt_main_2.raise_()
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(960, 20, 101, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.page)
        self.stackedWidget_4.setGeometry(QtCore.QRect(280, 60, 781, 631))
        self.stackedWidget_4.setStyleSheet("background-color: rgb(94,159,150);")
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.ex_class5_3 = QtWidgets.QPushButton(self.page_10)
        self.ex_class5_3.setGeometry(QtCore.QRect(470, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class5_3.setFont(font)
        self.ex_class5_3.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(170, 85, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class5_3.setObjectName("ex_class5_3")
        self.ex_class3_3 = QtWidgets.QPushButton(self.page_10)
        self.ex_class3_3.setGeometry(QtCore.QRect(120, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class3_3.setFont(font)
        self.ex_class3_3.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(170, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class3_3.setObjectName("ex_class3_3")
        self.ex_class2_3 = QtWidgets.QPushButton(self.page_10)
        self.ex_class2_3.setGeometry(QtCore.QRect(120, 270, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class2_3.setFont(font)
        self.ex_class2_3.setAutoFillBackground(False)
        self.ex_class2_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class2_3.setObjectName("ex_class2_3")
        self.ex_class6_3 = QtWidgets.QPushButton(self.page_10)
        self.ex_class6_3.setGeometry(QtCore.QRect(470, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class6_3.setFont(font)
        self.ex_class6_3.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class6_3.setObjectName("ex_class6_3")
        self.exercise_class_3 = QtWidgets.QLabel(self.page_10)
        self.exercise_class_3.setGeometry(QtCore.QRect(300, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exercise_class_3.setFont(font)
        self.exercise_class_3.setStyleSheet("")
        self.exercise_class_3.setObjectName("exercise_class_3")
        self.ex_class4_3 = QtWidgets.QPushButton(self.page_10)
        self.ex_class4_3.setGeometry(QtCore.QRect(470, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class4_3.setFont(font)
        self.ex_class4_3.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(0, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class4_3.setObjectName("ex_class4_3")
        self.ex_class1_3 = QtWidgets.QPushButton(self.page_10)
        self.ex_class1_3.setGeometry(QtCore.QRect(120, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ex_class1_3.setFont(font)
        self.ex_class1_3.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.ex_class1_3.setObjectName("ex_class1_3")
        self.stackedWidget_4.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.wrong_analyse = QtWidgets.QTextBrowser(self.page_11)
        self.wrong_analyse.setGeometry(QtCore.QRect(10, 490, 531, 151))
        self.wrong_analyse.setStyleSheet("background-color: rgb(94,159,150);")
        self.wrong_analyse.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wrong_analyse.setObjectName("wrong_analyse")
        self.Bt_A_ex_2 = QtWidgets.QPushButton(self.page_11)
        self.Bt_A_ex_2.setGeometry(QtCore.QRect(50, 220, 651, 31))
        self.Bt_A_ex_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(208, 206, 199);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"")
        self.Bt_A_ex_2.setObjectName("Bt_A_ex_2")
        self.Bt_D_ex_2 = QtWidgets.QPushButton(self.page_11)
        self.Bt_D_ex_2.setGeometry(QtCore.QRect(50, 400, 651, 31))
        self.Bt_D_ex_2.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(208, 206, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_D_ex_2.setObjectName("Bt_D_ex_2")
        self.wrong_view = QtWidgets.QPushButton(self.page_11)
        self.wrong_view.setGeometry(QtCore.QRect(660, 60, 71, 41))
        self.wrong_view.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.wrong_view.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color: rgb(198, 237, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"\n"
"")
        self.wrong_view.setObjectName("wrong_view")
        self.Bt_C_ex_2 = QtWidgets.QPushButton(self.page_11)
        self.Bt_C_ex_2.setGeometry(QtCore.QRect(50, 340, 651, 31))
        self.Bt_C_ex_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(208, 206, 199);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_C_ex_2.setObjectName("Bt_C_ex_2")
        self.wrong_title = QtWidgets.QTextBrowser(self.page_11)
        self.wrong_title.setGeometry(QtCore.QRect(20, 30, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.wrong_title.setFont(font)
        self.wrong_title.setStyleSheet("background-color: rgb(94,159,150);\n"
"")
        self.wrong_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wrong_title.setObjectName("wrong_title")
        self.wrong_next = QtWidgets.QPushButton(self.page_11)
        self.wrong_next.setGeometry(QtCore.QRect(590, 520, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wrong_next.setFont(font)
        self.wrong_next.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_next.setObjectName("wrong_next")
        self.Bt_B_ex_2 = QtWidgets.QPushButton(self.page_11)
        self.Bt_B_ex_2.setGeometry(QtCore.QRect(50, 280, 651, 31))
        self.Bt_B_ex_2.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(208, 206, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_B_ex_2.setObjectName("Bt_B_ex_2")
        self.wrong_back = QtWidgets.QPushButton(self.page_11)
        self.wrong_back.setGeometry(QtCore.QRect(10, 0, 41, 31))
        self.wrong_back.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    border-image: url(:/icon/res/icon/返回.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_back.setText("")
        self.wrong_back.setObjectName("wrong_back")
        self.stackedWidget_4.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.frame_13 = QtWidgets.QFrame(self.page_12)
        self.frame_13.setGeometry(QtCore.QRect(0, 30, 771, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.wrong_back_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_back_2.setGeometry(QtCore.QRect(320, 530, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wrong_back_2.setFont(font)
        self.wrong_back_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_back_2.setObjectName("wrong_back_2")
        self.line_2 = QtWidgets.QFrame(self.frame_13)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.text_info_2 = QtWidgets.QTextBrowser(self.frame_13)
        self.text_info_2.setGeometry(QtCore.QRect(10, 10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_info_2.setFont(font)
        self.text_info_2.setStyleSheet("background-color: rgb(94,159,150);")
        self.text_info_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_info_2.setObjectName("text_info_2")
        self.wrong_current_2 = QtWidgets.QTextBrowser(self.frame_13)
        self.wrong_current_2.setGeometry(QtCore.QRect(640, 30, 121, 81))
        self.wrong_current_2.setStyleSheet("background-color: rgb(94,159,150);")
        self.wrong_current_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wrong_current_2.setObjectName("wrong_current_2")
        self.wrong_Q1_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q1_2.setGeometry(QtCore.QRect(70, 150, 51, 51))
        self.wrong_Q1_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q1_2.setObjectName("wrong_Q1_2")
        self.label_title_2 = QtWidgets.QLabel(self.frame_13)
        self.label_title_2.setGeometry(QtCore.QRect(10, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title_2.setFont(font)
        self.label_title_2.setStyleSheet("border-bottom-left-radius:15px\n"
"\n"
"")
        self.label_title_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_title_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_title_2.setObjectName("label_title_2")
        self.wrong_Q2_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q2_2.setGeometry(QtCore.QRect(160, 150, 51, 51))
        self.wrong_Q2_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q2_2.setObjectName("wrong_Q2_2")
        self.wrong_Q5_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q5_2.setGeometry(QtCore.QRect(430, 150, 51, 51))
        self.wrong_Q5_2.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(244, 157, 170);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q5_2.setObjectName("wrong_Q5_2")
        self.wrong_Q4_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q4_2.setGeometry(QtCore.QRect(340, 150, 51, 51))
        self.wrong_Q4_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q4_2.setObjectName("wrong_Q4_2")
        self.wrong_Q3_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q3_2.setGeometry(QtCore.QRect(250, 150, 51, 51))
        self.wrong_Q3_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q3_2.setObjectName("wrong_Q3_2")
        self.wrong_Q7_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q7_2.setGeometry(QtCore.QRect(610, 150, 51, 51))
        self.wrong_Q7_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q7_2.setObjectName("wrong_Q7_2")
        self.wrong_Q10_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q10_2.setGeometry(QtCore.QRect(160, 250, 51, 51))
        self.wrong_Q10_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-radius:15px}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q10_2.setObjectName("wrong_Q10_2")
        self.wrong_Q9_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q9_2.setGeometry(QtCore.QRect(70, 250, 51, 51))
        self.wrong_Q9_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-radius:15px}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q9_2.setObjectName("wrong_Q9_2")
        self.wrong_Q8_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q8_2.setGeometry(QtCore.QRect(700, 150, 51, 51))
        self.wrong_Q8_2.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(244, 157, 170);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q8_2.setObjectName("wrong_Q8_2")
        self.wrong_Q6_2 = QtWidgets.QPushButton(self.frame_13)
        self.wrong_Q6_2.setGeometry(QtCore.QRect(520, 150, 51, 51))
        self.wrong_Q6_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(168, 239, 160);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.wrong_Q6_2.setObjectName("wrong_Q6_2")
        self.label_answersheet_2 = QtWidgets.QLabel(self.frame_13)
        self.label_answersheet_2.setGeometry(QtCore.QRect(330, 50, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_answersheet_2.setFont(font)
        self.label_answersheet_2.setObjectName("label_answersheet_2")
        self.stackedWidget_4.addWidget(self.page_12)
        self.label_drag.raise_()
        self.stackedWidget_4.raise_()
        self.frame_6.raise_()
        self.frame_4.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.frame_12 = QtWidgets.QFrame(self.page_8)
        self.frame_12.setGeometry(QtCore.QRect(40, 40, 221, 691))
        self.frame_12.setStyleSheet("QFrame{\n"
"    background-color: rgb(21,61,114);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.Bt_wrong_3 = QtWidgets.QPushButton(self.frame_12)
        self.Bt_wrong_3.setGeometry(QtCore.QRect(50, 360, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_wrong_3.setFont(font)
        self.Bt_wrong_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong_3.setObjectName("Bt_wrong_3")
        self.Bt_exercise_3 = QtWidgets.QPushButton(self.frame_12)
        self.Bt_exercise_3.setGeometry(QtCore.QRect(50, 220, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise_3.setFont(font)
        self.Bt_exercise_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise_3.setObjectName("Bt_exercise_3")
        self.Bt_main_3 = QtWidgets.QPushButton(self.frame_12)
        self.Bt_main_3.setGeometry(QtCore.QRect(50, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_main_3.setFont(font)
        self.Bt_main_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_main_3.setObjectName("Bt_main_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(0, 500, 221, 80))
        self.frame_14.setStyleSheet("background-color: rgb(94,159,150);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.Bt_setting_3 = QtWidgets.QPushButton(self.frame_14)
        self.Bt_setting_3.setGeometry(QtCore.QRect(50, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Bt_setting_3.setFont(font)
        self.Bt_setting_3.setStyleSheet("color:rgb(255,217,154)")
        self.Bt_setting_3.setObjectName("Bt_setting_3")
        self.frame_14.raise_()
        self.Bt_wrong_3.raise_()
        self.Bt_exercise_3.raise_()
        self.Bt_main_3.raise_()
        self.Bt_newacount = QtWidgets.QPushButton(self.page_8)
        self.Bt_newacount.setGeometry(QtCore.QRect(320, 530, 701, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_newacount.setFont(font)
        self.Bt_newacount.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_newacount.setObjectName("Bt_newacount")
        self.Bt_email = QtWidgets.QPushButton(self.page_8)
        self.Bt_email.setGeometry(QtCore.QRect(320, 370, 701, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_email.setFont(font)
        self.Bt_email.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_email.setObjectName("Bt_email")
        self.frame_11 = QtWidgets.QFrame(self.page_8)
        self.frame_11.setGeometry(QtCore.QRect(960, 30, 91, 121))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_8.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/最小化.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_9.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-image: url(:/icon/res/icon/关闭.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.Bt_setting_5 = QtWidgets.QPushButton(self.page_8)
        self.Bt_setting_5.setGeometry(QtCore.QRect(320, 450, 701, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_setting_5.setFont(font)
        self.Bt_setting_5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 154);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_setting_5.setObjectName("Bt_setting_5")
        self.label_4 = QtWidgets.QLabel(self.page_8)
        self.label_4.setGeometry(QtCore.QRect(600, 130, 141, 141))
        self.label_4.setStyleSheet("border-radius:60px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_drag_3 = QtWidgets.QLabel(self.page_8)
        self.label_drag_3.setGeometry(QtCore.QRect(260, 40, 821, 691))
        self.label_drag_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(94,159,150);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag_3.setText("")
        self.label_drag_3.setObjectName("label_drag_3")
        self.label_drag_3.raise_()
        self.Bt_setting_5.raise_()
        self.Bt_newacount.raise_()
        self.frame_11.raise_()
        self.Bt_email.raise_()
        self.label_4.raise_()
        self.frame_12.raise_()
        self.stackedWidget.addWidget(self.page_8)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_4.setCurrentIndex(0)
        self.pushButton.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_2.clicked.connect(Form.close) # type: ignore
        self.pushButton_6.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_7.clicked.connect(Form.close) # type: ignore
        self.pushButton_4.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_5.clicked.connect(Form.close) # type: ignore
        self.pushButton_8.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_9.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_3.setText(_translate("Form", "日历"))
        self.label.setText(_translate("Form", "刷题进度："))
        self.Bt_wrong.setText(_translate("Form", "错题"))
        self.Bt_exercise.setText(_translate("Form", "练习"))
        self.Bt_main.setText(_translate("Form", "首页"))
        self.Bt_setting.setText(_translate("Form", "我的"))
        self.label_3.setText(_translate("Form", "签到"))
        self.Bt_wrong_1.setText(_translate("Form", "错题"))
        self.Bt_setting_1.setText(_translate("Form", "我的"))
        self.Bt_exercise_1.setText(_translate("Form", "练习"))
        self.Bt_main_1.setText(_translate("Form", "首页"))
        self.ex_class5_2.setText(_translate("Form", "分类5"))
        self.ex_class3_2.setText(_translate("Form", "分类3"))
        self.ex_class2_2.setText(_translate("Form", "分类2"))
        self.ex_class6_2.setText(_translate("Form", "分类6"))
        self.exercise_class_2.setText(_translate("Form", "练习类别"))
        self.ex_class4_2.setText(_translate("Form", "分类4"))
        self.ex_class2_1.setText(_translate("Form", "分类1"))
        self.exercise_analyse.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">答案解析：可编辑（用户完成改题目后再显示），勾与叉在用户选择答案后判断其对错再显示</span></p></body></html>"))
        self.Bt_A_ex.setText(_translate("Form", "A.[1,2]"))
        self.Bt_D_ex.setText(_translate("Form", "C.[1,2]"))
        self.exercise_view.setText(_translate("Form", "答题卡"))
        self.Bt_C_ex.setText(_translate("Form", "D.[1,2]"))
        self.exercise_title.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">1.在平面直接坐标系中，函数y=(x+1)/(|x|+1)的图像上有三个不同的点位于直线l上，且这三个点的横坐标之和为0，求l的斜率的取值范围。且这三个点的横坐标之和为0，求l的斜率的取值范围。且这三个点的横坐标之和为0，求l的斜率的取值范围。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.exercise_next.setText(_translate("Form", "下一题"))
        self.Bt_B_ex.setText(_translate("Form", "B.[1,2]"))
        self.exercise_back2.setText(_translate("Form", "返回"))
        self.text_info.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">A同学</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">2025611011</span></p></body></html>"))
        self.wrong_current.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">当前题目：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">9</span><span style=\" font-size:10pt;\">/100</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.wrong_Q1.setText(_translate("Form", "1"))
        self.label_title.setText(_translate("Form", "题目"))
        self.wrong_Q2.setText(_translate("Form", "2"))
        self.wrong_Q5.setText(_translate("Form", "5"))
        self.wrong_Q4.setText(_translate("Form", "4"))
        self.wrong_Q3.setText(_translate("Form", "3"))
        self.wrong_Q7.setText(_translate("Form", "7"))
        self.wrong_Q10.setText(_translate("Form", "10"))
        self.wrong_Q9.setText(_translate("Form", "9"))
        self.wrong_Q8.setText(_translate("Form", "8"))
        self.wrong_Q6.setText(_translate("Form", "6"))
        self.label_answersheet.setText(_translate("Form", "答题卡"))
        self.Bt_exercise_2.setText(_translate("Form", "练习"))
        self.Bt_setting_2.setText(_translate("Form", "我的"))
        self.Bt_wrong_2.setText(_translate("Form", "错题"))
        self.Bt_main_2.setText(_translate("Form", "首页"))
        self.ex_class5_3.setText(_translate("Form", "分类5"))
        self.ex_class3_3.setText(_translate("Form", "分类3"))
        self.ex_class2_3.setText(_translate("Form", "分类2"))
        self.ex_class6_3.setText(_translate("Form", "分类6"))
        self.exercise_class_3.setText(_translate("Form", "练习类别"))
        self.ex_class4_3.setText(_translate("Form", "分类4"))
        self.ex_class1_3.setText(_translate("Form", "分类1"))
        self.wrong_analyse.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">答案解析：可编辑（用户完成改题目后再显示），勾与叉在用户选择答案后判断其对错再显示</span></p></body></html>"))
        self.Bt_A_ex_2.setText(_translate("Form", "A.[1,2]"))
        self.Bt_D_ex_2.setText(_translate("Form", "C.[1,2]"))
        self.wrong_view.setText(_translate("Form", "答题卡"))
        self.Bt_C_ex_2.setText(_translate("Form", "D.[1,2]"))
        self.wrong_title.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">1.在平面直接坐标系中，函数y=(x+1)/(|x|+1)的图像上有三个不同的点位于直线l上，且这三个点的横坐标之和为0，求l的斜率的取值范围。且这三个点的横坐标之和为0，求l的斜率的取值范围。且这三个点的横坐标之和为0，求l的斜率的取值范围。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.wrong_next.setText(_translate("Form", "下一题"))
        self.Bt_B_ex_2.setText(_translate("Form", "B.[1,2]"))
        self.wrong_back_2.setText(_translate("Form", "返回"))
        self.text_info_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">A同学</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">2025611011</span></p></body></html>"))
        self.wrong_current_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">当前题目：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">9</span><span style=\" font-size:10pt;\">/100</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.wrong_Q1_2.setText(_translate("Form", "1"))
        self.label_title_2.setText(_translate("Form", "题目"))
        self.wrong_Q2_2.setText(_translate("Form", "2"))
        self.wrong_Q5_2.setText(_translate("Form", "5"))
        self.wrong_Q4_2.setText(_translate("Form", "4"))
        self.wrong_Q3_2.setText(_translate("Form", "3"))
        self.wrong_Q7_2.setText(_translate("Form", "7"))
        self.wrong_Q10_2.setText(_translate("Form", "10"))
        self.wrong_Q9_2.setText(_translate("Form", "9"))
        self.wrong_Q8_2.setText(_translate("Form", "8"))
        self.wrong_Q6_2.setText(_translate("Form", "6"))
        self.label_answersheet_2.setText(_translate("Form", "答题卡"))
        self.Bt_wrong_3.setText(_translate("Form", "错题"))
        self.Bt_exercise_3.setText(_translate("Form", "练习"))
        self.Bt_main_3.setText(_translate("Form", "首页"))
        self.Bt_setting_3.setText(_translate("Form", "我的"))
        self.Bt_newacount.setText(_translate("Form", "切换账号"))
        self.Bt_email.setText(_translate("Form", "个人邮箱"))
        self.Bt_setting_5.setText(_translate("Form", "设置"))
        self.label_4.setText(_translate("Form", "     picture"))
import resource_rc
