# Generated by Django 4.2.6 on 2023-11-22 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='密码长度不能少于8个字符')], verbose_name='密码'),
        ),
    ]
