# Generated by Django 4.2.6 on 2023-12-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_computernetworksquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='题干')),
                ('question_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='题目图片')),
                ('answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='答案')),
                ('question_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='题型')),
            ],
        ),
    ]
