# Generated by Django 4.2.6 on 2023-12-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_question_option_1_question_option_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
