# Generated by Django 4.2.6 on 2023-12-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_question_mistakes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mistakes',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
