# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow_2(object):
    def setupUi(self, LoginWindow_2):
        LoginWindow_2.setObjectName("LoginWindow_2")
        LoginWindow_2.resize(1153, 740)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        LoginWindow_2.setFont(font)
        self.stackedWidget = QtWidgets.QStackedWidget(LoginWindow_2)
        self.stackedWidget.setGeometry(QtCore.QRect(120, 40, 981, 641))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.signin_button = QtWidgets.QPushButton(self.page_3)
        self.signin_button.setGeometry(QtCore.QRect(140, 460, 93, 28))
        self.signin_button.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"\n"
" color:  rgb(255, 255, 255)\n"
"}\n"
"")
        self.signin_button.setObjectName("signin_button")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(70, 20, 221, 571))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(92, 126, 168);\n"
"\n"
"\n"
"\n"
"border-top-left-radius:15px;\n"
"border-bottom-left-radius:15px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(130, 150, 111, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit.setGeometry(QtCore.QRect(100, 240, 161, 51))
        self.lineEdit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 671, 571))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,50);\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 671, 571))
        self.label_2.setStyleSheet("border-image: url(:/img/res/img/1107810.jpg);\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 310, 161, 51))
        self.lineEdit_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.login_button = QtWidgets.QPushButton(self.page_3)
        self.login_button.setGeometry(QtCore.QRect(120, 420, 131, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton{    \n"
"    background-color: rgb(180,160,160);\n"
"    \n"
"    color: rgb(248,250,255);\n"
"border-radius:20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
" background-color:  rgb(200,160,160)\n"
"}\n"
"")
        self.login_button.setObjectName("login_button")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(470, 140, 301, 141))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 210);")
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(self.page_3)
        self.frame.setGeometry(QtCore.QRect(860, 30, 79, 44))
        self.frame.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
" padding-bottom:5px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.min_button_3 = QtWidgets.QPushButton(self.frame)
        self.min_button_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_button_3.setIcon(icon)
        self.min_button_3.setObjectName("min_button_3")
        self.horizontalLayout_3.addWidget(self.min_button_3)
        self.max_button_3 = QtWidgets.QPushButton(self.frame)
        self.max_button_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_button_3.setIcon(icon1)
        self.max_button_3.setObjectName("max_button_3")
        self.horizontalLayout_3.addWidget(self.max_button_3)
        self.label.raise_()
        self.label_2.raise_()
        self.signin_button.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.login_button.raise_()
        self.label_5.raise_()
        self.frame.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.account_2 = QtWidgets.QLineEdit(self.page_4)
        self.account_2.setGeometry(QtCore.QRect(430, 170, 161, 51))
        self.account_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.account_2.setObjectName("account_2")
        self.signin = QtWidgets.QPushButton(self.page_4)
        self.signin.setGeometry(QtCore.QRect(440, 450, 131, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signin.setFont(font)
        self.signin.setStyleSheet("QPushButton{    \n"
"    background-color: rgb(180,160,160);\n"
"    \n"
"    color: rgb(248,250,255);\n"
"border-radius:20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
" background-color:  rgb(200,160,160)\n"
"}\n"
"")
        self.signin.setObjectName("signin")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(70, 20, 891, 571))
        self.label_11.setStyleSheet("background-image: url(:/img/res/img/1107810.jpg);\n"
"\n"
"border-radius:15px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.password_2 = QtWidgets.QLineEdit(self.page_4)
        self.password_2.setGeometry(QtCore.QRect(430, 220, 161, 51))
        self.password_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.account_had = QtWidgets.QPushButton(self.page_4)
        self.account_had.setGeometry(QtCore.QRect(460, 490, 93, 28))
        self.account_had.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"\n"
" color:  rgb(255, 255, 255)\n"
"}\n"
"")
        self.account_had.setObjectName("account_had")
        self.label_12 = QtWidgets.QLabel(self.page_4)
        self.label_12.setGeometry(QtCore.QRect(430, 80, 171, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.frame_3 = QtWidgets.QFrame(self.page_4)
        self.frame_3.setGeometry(QtCore.QRect(860, 30, 79, 44))
        self.frame_3.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
" padding-bottom:5px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.min_button_5 = QtWidgets.QPushButton(self.frame_3)
        self.min_button_5.setText("")
        self.min_button_5.setIcon(icon)
        self.min_button_5.setObjectName("min_button_5")
        self.horizontalLayout_5.addWidget(self.min_button_5)
        self.max_button_5 = QtWidgets.QPushButton(self.frame_3)
        self.max_button_5.setText("")
        self.max_button_5.setIcon(icon1)
        self.max_button_5.setObjectName("max_button_5")
        self.horizontalLayout_5.addWidget(self.max_button_5)
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(430, 120, 141, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.password_confirmed = QtWidgets.QLineEdit(self.page_4)
        self.password_confirmed.setGeometry(QtCore.QRect(430, 270, 161, 51))
        self.password_confirmed.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.password_confirmed.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_confirmed.setObjectName("password_confirmed")
        self.PhoneNumber = QtWidgets.QLineEdit(self.page_4)
        self.PhoneNumber.setGeometry(QtCore.QRect(430, 320, 161, 51))
        self.PhoneNumber.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.PhoneNumber.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PhoneNumber.setObjectName("PhoneNumber")
        self.email = QtWidgets.QLineEdit(self.page_4)
        self.email.setGeometry(QtCore.QRect(430, 370, 161, 51))
        self.email.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.email.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email.setObjectName("email")
        self.label_11.raise_()
        self.account_2.raise_()
        self.signin.raise_()
        self.password_2.raise_()
        self.account_had.raise_()
        self.label_12.raise_()
        self.frame_3.raise_()
        self.label_13.raise_()
        self.password_confirmed.raise_()
        self.PhoneNumber.raise_()
        self.email.raise_()
        self.stackedWidget.addWidget(self.page_4)

        self.retranslateUi(LoginWindow_2)
        self.stackedWidget.setCurrentIndex(0)
        self.min_button_3.clicked.connect(LoginWindow_2.showMinimized) # type: ignore
        self.max_button_3.clicked.connect(LoginWindow_2.close) # type: ignore
        self.min_button_5.clicked.connect(LoginWindow_2.showMinimized) # type: ignore
        self.max_button_5.clicked.connect(LoginWindow_2.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow_2)

    def retranslateUi(self, LoginWindow_2):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow_2.setWindowTitle(_translate("LoginWindow_2", "Form"))
        self.signin_button.setText(_translate("LoginWindow_2", "注册账号"))
        self.label_4.setText(_translate("LoginWindow_2", "欢迎登录"))
        self.lineEdit.setPlaceholderText(_translate("LoginWindow_2", "账号："))
        self.lineEdit_2.setPlaceholderText(_translate("LoginWindow_2", "密码："))
        self.login_button.setText(_translate("LoginWindow_2", "登录"))
        self.label_5.setText(_translate("LoginWindow_2", "“若你决定灿烂，\n"
" 山无遮，\n"
" 海无拦！”"))
        self.account_2.setPlaceholderText(_translate("LoginWindow_2", "账号："))
        self.signin.setText(_translate("LoginWindow_2", "注册"))
        self.password_2.setPlaceholderText(_translate("LoginWindow_2", "密码："))
        self.account_had.setText(_translate("LoginWindow_2", "已有账号"))
        self.label_12.setText(_translate("LoginWindow_2", "欢迎注册研题"))
        self.label_13.setText(_translate("LoginWindow_2", "每一天，乐在考研。"))
        self.password_confirmed.setPlaceholderText(_translate("LoginWindow_2", "确认密码："))
        self.PhoneNumber.setPlaceholderText(_translate("LoginWindow_2", "手机号码："))
        self.email.setPlaceholderText(_translate("LoginWindow_2", "邮箱："))
import resource_rc
