# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '练习UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_practice2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 30, 221, 691))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(198, 237, 255);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Bt_mine = QtWidgets.QPushButton(self.frame_2)
        self.Bt_mine.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Bt_mine.setFont(font)
        self.Bt_mine.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 247, 217);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_mine.setObjectName("Bt_mine")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 100, 221, 80))
        self.frame_3.setStyleSheet("background-color: rgb(229, 255, 248);\n"
"border-radius:0px\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Bt_wrong = QtWidgets.QPushButton(self.frame_3)
        self.Bt_wrong.setGeometry(QtCore.QRect(50, 10, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.Bt_wrong.setFont(font)
        self.Bt_wrong.setStyleSheet("QPushButton{    \n"
"background-color: rgb(229, 255, 248);\n"
"    border-radius:30px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong.setObjectName("Bt_wrong")
        self.Bt_exercise = QtWidgets.QPushButton(self.frame_2)
        self.Bt_exercise.setGeometry(QtCore.QRect(50, 300, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise.setFont(font)
        self.Bt_exercise.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 247, 217);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise.setObjectName("Bt_exercise")
        self.text_wronganalyse = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_wronganalyse.setGeometry(QtCore.QRect(310, 550, 531, 151))
        self.text_wronganalyse.setStyleSheet("background-color: rgb(229, 255, 248);")
        self.text_wronganalyse.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_wronganalyse.setObjectName("text_wronganalyse")
        self.test_wrong = QtWidgets.QTextBrowser(self.centralwidget)
        self.test_wrong.setGeometry(QtCore.QRect(320, 80, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.test_wrong.setFont(font)
        self.test_wrong.setStyleSheet("background-color: rgb(229, 255, 248);\n"
"")
        self.test_wrong.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.test_wrong.setObjectName("test_wrong")
        self.Bt_C = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_C.setGeometry(QtCore.QRect(350, 460, 651, 31))
        self.Bt_C.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(208, 206, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_C.setObjectName("Bt_C")
        self.Bt_D = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_D.setGeometry(QtCore.QRect(350, 400, 651, 31))
        self.Bt_D.setStyleSheet("QPushButton{\n"
"background-color: rgb(208, 206, 199);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_D.setObjectName("Bt_D")
        self.Bt_B = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_B.setGeometry(QtCore.QRect(350, 340, 651, 31))
        self.Bt_B.setStyleSheet("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(208, 206, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_B.setObjectName("Bt_B")
        self.Bt_A = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_A.setGeometry(QtCore.QRect(350, 280, 651, 31))
        self.Bt_A.setStyleSheet("QPushButton{\n"
"background-color: rgb(208, 206, 199);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"")
        self.Bt_A.setObjectName("Bt_A")
        self.Bt_next = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_next.setGeometry(QtCore.QRect(890, 580, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Bt_next.setFont(font)
        self.Bt_next.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_next.setObjectName("Bt_next")
        self.Bt_view = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_view.setGeometry(QtCore.QRect(960, 100, 71, 41))
        self.Bt_view.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.Bt_view.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color: rgb(198, 237, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"\n"
"")
        self.Bt_view.setObjectName("Bt_view")
        self.label_drag = QtWidgets.QLabel(self.centralwidget)
        self.label_drag.setGeometry(QtCore.QRect(240, 30, 821, 691))
        self.label_drag.setStyleSheet("QFrame{\n"
"    background-color: rgb(229, 255, 248);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"\n"
"}")
        self.label_drag.setText("")
        self.label_drag.setObjectName("label_drag")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(950, 30, 51, 51))
        self.pushButton.setStyleSheet("border-image: url(:/新前缀/最小化.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1010, 40, 31, 31))
        self.pushButton_2.setStyleSheet("border-image: url(:/新前缀/关闭窗口.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 280, 31, 31))
        self.pushButton_3.setStyleSheet("border-image: url(:/新前缀/对勾-解除.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 330, 41, 41))
        self.pushButton_4.setStyleSheet("border-image: url(:/新前缀/错误.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_drag.raise_()
        self.Bt_A.raise_()
        self.Bt_D.raise_()
        self.text_wronganalyse.raise_()
        self.Bt_C.raise_()
        self.Bt_view.raise_()
        self.Bt_B.raise_()
        self.test_wrong.raise_()
        self.Bt_next.raise_()
        self.frame_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bt_mine.setText(_translate("MainWindow", "我的"))
        self.Bt_wrong.setText(_translate("MainWindow", "练习"))
        self.Bt_exercise.setText(_translate("MainWindow", "错题"))
        self.text_wronganalyse.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">答案解析：可编辑（用户完成改题目后再显示），勾与叉在用户选择答案后判断其对错再显示</span></p></body></html>"))
        self.test_wrong.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">1.在平面直接坐标系中，函数y=(x+1)/(|x|+1)的图像上有三个不同的点位于直线l上，且这三个点的横坐标之和为0，求l的斜率的取值范围。且这三个点的横坐标之和为0，求l的斜率的取值范围。且这三个点的横坐标之和为0，求l的斜率的取值范围。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.Bt_C.setText(_translate("MainWindow", "C.[1,2]"))
        self.Bt_D.setText(_translate("MainWindow", "D.[1,2]"))
        self.Bt_B.setText(_translate("MainWindow", "B.[1,2]"))
        self.Bt_A.setText(_translate("MainWindow", "A.[1,2]"))
        self.Bt_next.setText(_translate("MainWindow", "下一题"))
        self.Bt_view.setText(_translate("MainWindow", "答题卡"))
import Resources_rc
