# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '错题UI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_wrong(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1080, 727)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setAcceptDrops(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 791, 671))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Bt_wrong1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_wrong1.setGeometry(QtCore.QRect(400, 150, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bt_wrong1.setFont(font)
        self.Bt_wrong1.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong1.setObjectName("Bt_wrong1")
        self.Bt_wrong2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_wrong2.setGeometry(QtCore.QRect(400, 300, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bt_wrong2.setFont(font)
        self.Bt_wrong2.setAutoFillBackground(False)
        self.Bt_wrong2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong2.setObjectName("Bt_wrong2")
        self.Bt_wrong3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_wrong3.setGeometry(QtCore.QRect(400, 450, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bt_wrong3.setFont(font)
        self.Bt_wrong3.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(170, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong3.setObjectName("Bt_wrong3")
        self.Bt_wrong4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_wrong4.setGeometry(QtCore.QRect(750, 150, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bt_wrong4.setFont(font)
        self.Bt_wrong4.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(0, 255, 127);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong4.setObjectName("Bt_wrong4")
        self.Bt_wrong5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_wrong5.setGeometry(QtCore.QRect(750, 300, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bt_wrong5.setFont(font)
        self.Bt_wrong5.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(170, 85, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong5.setObjectName("Bt_wrong5")
        self.Bt_wrong6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_wrong6.setGeometry(QtCore.QRect(750, 450, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bt_wrong6.setFont(font)
        self.Bt_wrong6.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 255);\n"
"    border-radius:15px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong6.setObjectName("Bt_wrong6")
        self.Bt_mini = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_mini.setGeometry(QtCore.QRect(970, 20, 51, 51))
        self.Bt_mini.setStyleSheet("border:none;\n"
"border-image: url(:/新前缀/最小化.png);")
        self.Bt_mini.setText("")
        self.Bt_mini.setObjectName("Bt_mini")
        self.Bt_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_exit.setGeometry(QtCore.QRect(1020, 30, 31, 31))
        self.Bt_exit.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-image: url(:/新前缀/关闭窗口.png);\n"
"}\n"
"")
        self.Bt_exit.setText("")
        self.Bt_exit.setObjectName("Bt_exit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 221, 691))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(198, 237, 255);\n"
"    border-top-left-radius:30px;\n"
"    border-bottom-left-radius:30px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Bt_exercise = QtWidgets.QPushButton(self.frame)
        self.Bt_exercise.setGeometry(QtCore.QRect(50, 100, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.Bt_exercise.setFont(font)
        self.Bt_exercise.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 247, 217);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_exercise.setObjectName("Bt_exercise")
        self.Bt_mine = QtWidgets.QPushButton(self.frame)
        self.Bt_mine.setGeometry(QtCore.QRect(50, 500, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Bt_mine.setFont(font)
        self.Bt_mine.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 247, 217);\n"
"    border-radius:30px\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_mine.setObjectName("Bt_mine")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 300, 221, 80))
        self.frame_2.setStyleSheet("background-color: rgb(229, 255, 248);\n"
"border-radius:0px\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Bt_wrong = QtWidgets.QPushButton(self.frame_2)
        self.Bt_wrong.setGeometry(QtCore.QRect(50, 10, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.Bt_wrong.setFont(font)
        self.Bt_wrong.setStyleSheet("QPushButton{    \n"
"background-color: rgb(229, 255, 248);\n"
"    border-radius:30px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Bt_wrong.setObjectName("Bt_wrong")
        self.label_drag = QtWidgets.QLabel(self.centralwidget)
        self.label_drag.setGeometry(QtCore.QRect(250, 10, 821, 691))
        self.label_drag.setStyleSheet("QFrame{\n"
"    background-color: rgb(229, 255, 248);\n"
"    border-top-right-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.label_drag.setText("")
        self.label_drag.setObjectName("label_drag")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 60, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_drag.raise_()
        self.label_2.raise_()
        self.Bt_wrong1.raise_()
        self.Bt_wrong2.raise_()
        self.Bt_wrong3.raise_()
        self.Bt_wrong4.raise_()
        self.Bt_wrong5.raise_()
        self.Bt_wrong6.raise_()
        self.Bt_mini.raise_()
        self.Bt_exit.raise_()
        self.frame.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Bt_exit.clicked.connect(MainWindow.close) # type: ignore
        self.Bt_mini.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bt_wrong1.setText(_translate("MainWindow", "分类1"))
        self.Bt_wrong2.setText(_translate("MainWindow", "分类2"))
        self.Bt_wrong3.setText(_translate("MainWindow", "分类3"))
        self.Bt_wrong4.setText(_translate("MainWindow", "分类4"))
        self.Bt_wrong5.setText(_translate("MainWindow", "分类5"))
        self.Bt_wrong6.setText(_translate("MainWindow", "分类6"))
        self.Bt_exercise.setText(_translate("MainWindow", "练习"))
        self.Bt_mine.setText(_translate("MainWindow", "我的"))
        self.Bt_wrong.setText(_translate("MainWindow", "错题"))
        self.label.setText(_translate("MainWindow", "错题类别"))
import Resources_rc
