# Generated by Django 4.2.6 on 2023-12-10 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='问题ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile', verbose_name='用户ID')),
            ],
        ),
    ]
