# Generated by Django 4.2.6 on 2023-12-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_userprofile_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_picture',
        ),
    ]
